### ISSUE TITLE
Issue missing 'Webkit' on Fedora 25

### ISSUE THREAD

**Issue by GinoHereIam** [michaldaniel/Ebook-Viewer#17]
Hi,

can you take a look?

```Python
gino@gino-xps13:/tmp$ easy-ebook-viewer 
Traceback (most recent call last):
  File "/usr/share/easy-ebook-viewer/main.py", line 20, in <module>
    from main_window import MainWindow
  File "/usr/share/easy-ebook-viewer/main_window.py", line 21, in <module>
    from components import header_bar, viewer, chapters_list
  File "/usr/share/easy-ebook-viewer/components/viewer.py", line 19, in <module>
    gi.require_version('WebKit', '3.0')
  File "/usr/lib64/python3.5/site-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit not available
```
Best regards
Gino

**Comment by GinoHereIam** [comment]
Fixed, can you make clear to install webkit for gtk3 please? :D

**Comment by michaldaniel** [comment]
@GinoHereIam Yes. Thanks.
