### ISSUE TITLE
Namespace WebKit not available in Ubuntu 19.04

### ISSUE THREAD

**Issue by diegolagoglez** [michaldaniel/ebook-viewer#48]
I have a fresh install of Ubuntu 19.04 and once installed all dependencies this error is raised on every launch:

```
easy-ebook-viewer 
Traceback (most recent call last):
  File "/usr/share/easy-ebook-viewer/main.py", line 21, in <module>
    from main_window import MainWindow
  File "/usr/share/easy-ebook-viewer/main_window.py", line 21, in <module>
    from components import header_bar, viewer, chapters_list
  File "/usr/share/easy-ebook-viewer/components/viewer.py", line 19, in <module>
    gi.require_version('WebKit', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit not available
```

**Comment by jigarWala** [comment]
you need to do
`sudo apt install gir1.2-webkit-3.0`

**Comment by diegolagoglez** [comment]
> you need to do
> `sudo apt install gir1.2-webkit-3.0`

This package is not available in Ubuntu 19.04.

I'll try to install from other sources.

**Comment by jigarWala** [comment]
:+1: :
