### ISSUE TITLE
Application fails opening eBook

### ISSUE THREAD

**Issue by diegolagoglez** [michaldaniel/ebook-viewer#49]
The application (version 1.0-g09995b1) fails opening [this eBook](https://www.vmwareporvexperts.org/#!/books):

```bash
user@box ~ $ easy-ebook-viewer VMware-por-vExperts-libro.epub 

(main.py:28993): GLib-GIO-CRITICAL **: g_application_set_application_id: assertion 'application_id == NULL || g_application_id_is_valid (application_id)' failed
Displaying blank page.
Traceback (most recent call last):
  File "/home/diego/Projects/Ebook-Viewer/src/main.py", line 54, in do_activate
    self.window = MainWindow(file_path=self.file_path)
  File "/home/diego/Projects/Ebook-Viewer/src/main_window.py", line 113, in __init__
    self.load_book_data(sys.argv[1])
  File "/home/diego/Projects/Ebook-Viewer/src/main_window.py", line 327, in load_book_data
    self.__continiue_book_loading(filename)
  File "/home/diego/Projects/Ebook-Viewer/src/main_window.py", line 275, in __continiue_book_loading
    if self.content_provider.prepare_book(filename):
  File "/home/diego/Projects/Ebook-Viewer/src/workers/content_provider.py", line 123, in prepare_book
    self.__load_titles_and_files()
  File "/home/diego/Projects/Ebook-Viewer/src/workers/content_provider.py", line 208, in __load_titles_and_files
    if os.access(ncx_file_path, os.R_OK):  # Checks if NCX is accessible
TypeError: access: can't specify None for path argument
```

**Comment by NMelis** [comment]
and 
```
> easy-ebook-viewer 
Traceback (most recent call last):
  File "/usr/share/easy-ebook-viewer/main.py", line 21, in <module>
    from main_window import MainWindow
  File "/usr/share/easy-ebook-viewer/main_window.py", line 21, in <module>
    from components import header_bar, viewer, chapters_list
  File "/usr/share/easy-ebook-viewer/components/viewer.py", line 19, in <module>
    gi.require_version('WebKit', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit not available

```
